add_library(
    dxa_simulation
    STATIC
        src/AiDecision.cpp
        src/BehaviorTree.cpp
        src/Combat.cpp
        src/MatchConfig.cpp
        src/Math2.cpp
        src/NavAgent.cpp
        src/NavMesh.cpp
        src/NavMeshGrid.cpp
        src/NavMeshPath.cpp
        src/SafeZone.cpp
        src/SpatialIndex.cpp
)
target_include_directories(
    dxa_simulation
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)
dxa_enable_project_warnings(dxa_simulation)
